// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BCard: typeof import('bootstrap-vue-3')['BCard']
    BCardBody: typeof import('bootstrap-vue-3')['BCardBody']
    BCardTitle: typeof import('bootstrap-vue-3')['BCardTitle']
    BCol: typeof import('bootstrap-vue-3')['BCol']
    BFormCheckbox: typeof import('bootstrap-vue-3')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-3')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BListGroup: typeof import('bootstrap-vue-3')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-3')['BListGroupItem']
    BNavbar: typeof import('bootstrap-vue-3')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-3')['BNavbarBrand']
    BRow: typeof import('bootstrap-vue-3')['BRow']
    ForgotPassword: typeof import('./src/components/ForgotPassword.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./src/components/SignIn.vue')['default']
    SignUp: typeof import('./src/components/SignUp.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
