version: "3.8"
services:

  frontend:
    build: 
      context: ./frontend
      target: development
    volumes:
      - "./frontend/src:/frontend/src"
      - "./frontend/public:/frontend/public"
    ports:
      - "3000:3000"
  
  backend:
    build: 
      context: ./backend
      target: development
    depends_on:
      - "mongo"
    ports:
      - "8000:8000"
    volumes:
    - "./backend/app:/backend/app"
    - "./backend/tests:/backend/tests"

  mongo:
    image: mongo:6.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongod
      MONGO_INITDB_ROOT_PASSWORD: Password123!
      MONGO_INITDB_DATABASE: your_app
    volumes:
      - "mongo:/data/db"
      - "./dev/init-db.js:/docker-entrypoint-initdb.d/init-db.js"
    expose:
      - "27017"
    restart: unless-stopped

volumes:
  mongo: